import argparse
import csv
import os
import sys
from collections import Counter
from typing import Dict, List, Tuple

import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.model_selection import train_test_split

CURRENT_DIR = os.path.dirname(__file__)
PROJECT_DIR = os.path.abspath(os.path.join(CURRENT_DIR, ".."))
if PROJECT_DIR not in sys.path:
    sys.path.insert(0, PROJECT_DIR)

from app.vision.fingering_classifier import ChordClassifier


def parse_args():
    parser = argparse.ArgumentParser(
        description="Train and save the guitar chord classifier from captured landmark CSV data."
    )
    parser.add_argument(
        "--input",
        default=os.path.join(PROJECT_DIR, "data", "chord_landmarks.csv"),
        help="CSV generated by scripts/collect_data.py",
    )
    parser.add_argument(
        "--model-path",
        default=os.path.join(PROJECT_DIR, "app", "models", "chord_classifier.pkl"),
        help="Path where the trained pickle model should be saved",
    )
    parser.add_argument("--test-size", type=float, default=0.2, help="Evaluation split size")
    parser.add_argument("--trees", type=int, default=200, help="RandomForest n_estimators")
    parser.add_argument("--random-state", type=int, default=42, help="Reproducible split/model seed")
    return parser.parse_args()


def row_to_landmarks(row: Dict[str, str]) -> List[Dict[str, float]]:
    landmarks = []
    for idx in range(21):
        landmarks.append(
            {
                "x": float(row[f"x{idx}"]),
                "y": float(row[f"y{idx}"]),
                "z": float(row[f"z{idx}"]),
            }
        )
    return landmarks


def load_dataset(csv_path: str) -> Tuple[np.ndarray, np.ndarray]:
    if not os.path.exists(csv_path):
        raise SystemExit(f"Dataset not found: {csv_path}")

    classifier = ChordClassifier(model_path="")
    features = []
    labels = []

    with open(csv_path, newline="", encoding="utf-8") as csv_file:
        reader = csv.DictReader(csv_file)
        required_fields = {"label", *[f"{axis}{idx}" for idx in range(21) for axis in ("x", "y", "z")]}
        missing = required_fields - set(reader.fieldnames or [])
        if missing:
            missing_list = ", ".join(sorted(missing))
            raise SystemExit(f"Dataset is missing required columns: {missing_list}")

        for row_number, row in enumerate(reader, start=2):
            label = row["label"].strip()
            if not label:
                print(f"Skipping row {row_number}: empty label")
                continue

            try:
                features.append(classifier.extract_features(row_to_landmarks(row)))
                labels.append(label)
            except (KeyError, ValueError) as exc:
                print(f"Skipping row {row_number}: {exc}")

    if not features:
        raise SystemExit("No valid landmark rows found in dataset.")

    return np.array(features), np.array(labels)


def can_stratify(labels: np.ndarray, test_size: float) -> bool:
    counts = Counter(labels)
    test_count = int(round(len(labels) * test_size))
    return min(counts.values()) >= 2 and test_count >= len(counts)


def main():
    args = parse_args()
    if not 0.0 < args.test_size < 1.0:
        raise SystemExit("--test-size must be between 0 and 1")
    if args.trees <= 0:
        raise SystemExit("--trees must be greater than 0")

    X, y = load_dataset(args.input)
    label_counts = Counter(y)
    if len(label_counts) < 2:
        raise SystemExit("Training requires at least two chord labels.")

    stratify = y if can_stratify(y, args.test_size) else None
    X_train, X_test, y_train, y_test = train_test_split(
        X,
        y,
        test_size=args.test_size,
        random_state=args.random_state,
        stratify=stratify,
    )

    eval_model = RandomForestClassifier(
        n_estimators=args.trees,
        random_state=args.random_state,
        class_weight="balanced",
    )
    eval_model.fit(X_train, y_train)
    predictions = eval_model.predict(X_test)

    print("Dataset class distribution:")
    for label, count in sorted(label_counts.items()):
        print(f"  {label}: {count}")

    print(f"\nHoldout accuracy: {accuracy_score(y_test, predictions):.3f}")
    print("\nClassification report:")
    print(classification_report(y_test, predictions, zero_division=0))
    print("Confusion matrix labels:", list(eval_model.classes_))
    print(confusion_matrix(y_test, predictions, labels=eval_model.classes_))

    final_model = RandomForestClassifier(
        n_estimators=args.trees,
        random_state=args.random_state,
        class_weight="balanced",
    )
    final_model.fit(X, y)

    classifier = ChordClassifier(model_path=args.model_path)
    classifier.model = final_model
    classifier.save_model()


if __name__ == "__main__":
    main()
